# @since 2.5 Admin in now in CoreBundle
services:
    sonata.admin.customer:
        class: Ecedi\Donate\CoreBundle\Admin\CustomerAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: donation
              label: "edonate.admin.model.customers"
              label_catalogue: "sonata-admin"
              pager_type: "simple"

        arguments:
            - ~
            - Ecedi\Donate\CoreBundle\Entity\Customer
            - ~
        calls:
            - [ setTranslationDomain, [sonata-admin]]
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
            - [ setTemplate, [show, DonateCoreBundle:Admin:Customer/show.html.twig]]

    sonata.admin.intent:
        class: Ecedi\Donate\CoreBundle\Admin\IntentAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: donation
              label: "edonate.admin.model.intents"
              label_catalogue: "sonata-admin"

        arguments:
            - ~
            - Ecedi\Donate\CoreBundle\Entity\Intent
            - ~
        calls:
            - [ setTranslationDomain, [sonata-admin]]
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
