language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.5


before_script:
  - composer install -n
  - app/console doctrine:database:create -e test
  - app/console doctrine:schema:create -e test
  - app/console ca:cl -e test

script:
   - ./bin/phpspec run --format=pretty
   - ./bin/behat --format=pretty
