imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: warning
            handler:      nested
        nested:
            type:  rotating_file
            path:  /var/log/ecollecte/%kernel.environment%.log
            level: warning
            max_files: 3

        # info:
        #     type: stream
        #     path:  %kernel.logs_dir%/%kernel.environment%-info.log
        #     level: info

donate_ogone:
    prod: true
