# DonateAdminBundle/Resources/config/services.yml
# @since 2.1.0
parameters:
    donate_admin.analytics.client_id :
    donate_admin.analytics.data_ids :
    donate_admin.analytics.api_key :

services:
    ecollect.export.customer:
        class : Ecedi\Donate\AdminBundle\Exporter\CustomerExporter
        arguments : ['@translator']

    ecollect.export.intent:
        class : Ecedi\Donate\AdminBundle\Exporter\IntentExporter
        arguments: ['@translator']

    ecollect.form.customer:
        class : Ecedi\Donate\AdminBundle\Form\CustomerType
        tags:
            - {name: form.type, alias: customer}

    ecollect.form.layout:
        class: Ecedi\Donate\AdminBundle\Form\LayoutType
        tags:
            - {name: form.type, alias: layout}

    ecollect.form.block:
        class: Ecedi\Donate\AdminBundle\Form\BlockType
        tags:
            - {name: form.type, alias: block}

    # ecollect.form.affectation:
    #     class: Ecedi\Donate\AdminBundle\Form\AffectationType
    #     tags:
    #         - {name: form.type, alias: affectation}

    ecollect.form.customer_filters:
        class: Ecedi\Donate\AdminBundle\Form\CustomerFiltersType
        tags:
            - {name: form.type, alias: customer_filters}

    ecollect.form.intent_filters:
        class: Ecedi\Donate\AdminBundle\Form\IntentFiltersType
        tags:
            - {name: form.type, alias: intent_filters}
